### ISSUE TITLE
VI can't create a swap file when mounted in lind-fuse

### ISSUE THREAD

**Issue by cmatthew** [cmatthew/Lind-misc#56] opened 2012-10-15 19:13 UTC
The lind FS fails to make a VI swap file when it is run in  a lind fuse mounted directory.

**Comment by JustinCappos** [comment] 2012-10-15 19:40
Possibly due to disallowed file name (starting with '.')?

**Comment by cmatthew** [comment] 2012-10-15 19:50
We should not disallow any file names though, right?  our files are called
linddata.01 etc.

On Mon, Oct 15, 2012 at 12:40 PM, JustinCappos notifications@github.comwrote:

> Possibly due to disallowed file name (starting with '.')?
> 
> On Mon, Oct 15, 2012 at 3:13 PM, Chris Matthews notifications@github.comwrote:
> 
> > The lind FS fails to make a VI swap file when it is run in a lind fuse
> > mounted directory.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cmatthew/Lind-misc/issues/56>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cmatthew/Lind-misc/issues/56#issuecomment-9458646.

## 

Chris Matthews
http://www.christophermatthews.ca

**Comment by JustinCappos** [comment] 2012-10-15 23:21
Well, I'm not sure what the implementation does.   I think some types of
names are FS specific and I don't recall what I did.

Thanks,
Justin

**Comment by NitinJami** [comment] 2012-10-16 02:20
I think I found the problem and its not because of restrictions on file names. Lind is allowing us to create any kind of file name.

The problem is with the way vim works, so If you create a file with vim for first time, it is fine, you can write to it and exit, the swap file gets created and deleted.

The problem arises when we are trying to append the file using vim, so if we once again open the file, vim actually tries to store a backup copy. It renames the original file to demo.txt~, and then opens up a new file with same name but copying the contents from demo.txt~.

Now, something crazy happens here and it doesn't allow us to write into the file anymore, the error's that are generated are on following files:

1 .demo.txt.swp (becomes a non-regular file), hence the unlink fails since we are raising error on non-regular files
http://tinyurl.com/close-helper

2 demo.txt~ cannot be found in the filesystemmetadata to get deleted, this must be either due to the way we are implementing rename_syscall or something else that I need to find

**Comment by NitinJami** [comment] 2012-10-18 02:56
rename_syscall has been fixed, so the second error is resolved. The first error might be causing due to append failing in lind, I filed bug for it.

**Comment by NitinJami** [comment] 2012-10-18 03:13
Nope, that didn't solve the problem, I am not sure whether its a fuse problem or our syscalls.

**Comment by NitinJami** [comment] 2012-10-27 22:07
Apparently, chmod wasn't correctly setting the flags for a file. This would make a regular file as a non-regular file. This made the write failing into the swap file.

FIXED in revision# 6018

**Closed as completed by NitinJami** 2012-10-27 22:07 UTC
Labels: Filesystem, Fuse
